# Day 5: Tensor Implementation Notebook

This notebook contains complete implementations of all 17 tensor tasks from Assignment 3.

In [1]:
import numpy as np
import torch

print("NumPy version:", np.__version__)
print("PyTorch version:", torch.__version__)

NumPy version: 2.4.6
PyTorch version: 2.12.1+cpu


## Task 1: Create a Tensor

In [2]:
sensor_readings = np.array([25.2, 25.5, 24.9, 26.1, 25.8])

print(f"Tensor: {sensor_readings}")
print(f"Shape: {sensor_readings.shape}")
print(f"Number of dimensions (ndim): {sensor_readings.ndim}")
print(f"Number of elements (size): {sensor_readings.size}")

Tensor: [25.2 25.5 24.9 26.1 25.8]
Shape: (5,)
Number of dimensions (ndim): 1
Number of elements (size): 5


## Task 2: From Vector to Matrix

In [3]:
temperature = np.array([25, 26, 25, 27, 28])
pressure = np.array([101, 102, 101, 103, 104])
humidity = np.array([60, 62, 61, 63, 64])
vibration = np.array([0.2, 0.3, 0.2, 0.4, 0.5])

X = np.column_stack([temperature, pressure, humidity, vibration])

print(f"Shape: {X.shape}")
print(f"Number of dimensions: {X.ndim}")
print(f"First time step (row 0): {X[0]}")
print(f"Temperature readings (col 0): {X[:, 0]}")
print(f"Vibration readings (col 3): {X[:, 3]}")

Shape: (5, 4)
Number of dimensions: 2
First time step (row 0): [ 25.  101.   60.    0.2]
Temperature readings (col 0): [25. 26. 25. 27. 28.]
Vibration readings (col 3): [0.2 0.3 0.2 0.4 0.5]


## Task 3: Create a 3D Tensor

In [4]:
np.random.seed(42)
X = np.random.randn(10, 5, 4) * 10 + 25

print(f"Shape: {X.shape}")
print("Dimensions: Machine × Time × Sensor")

# Temperature of machine 3 at time step 2
temp_m3_t2 = X[3, 2, 0]
print(f"\nTemperature of machine 3 at time step 2: {temp_m3_t2:.2f}")

# All sensor readings of machine 5
machine_5 = X[5]
print(f"\nAll sensor readings of machine 5 (shape {machine_5.shape}):")
print(machine_5)

# All machines at time step 1
time_step_1 = X[:, 1, :]
print(f"\nAll machines at time step 1 (shape {time_step_1.shape}):")
print(time_step_1)

# Sensor 4 from all machines and time steps
sensor_4 = X[:, :, 3]
print(f"\nSensor 4 readings (shape {sensor_4.shape}):")
print(sensor_4)

Shape: (10, 5, 4)
Dimensions: Machine × Time × Sensor

Temperature of machine 3 at time step 2: 28.62

All sensor readings of machine 5 (shape (5, 4)):
[[10.84629258 20.79354677 21.57285483 16.97722731]
 [23.38714288 29.04050857 43.86185901 26.74577813]
 [27.57550391 24.25554084  5.81228785 24.73486125]
 [25.6023021  49.63242112 23.07639035 28.01547342]
 [24.6528823  13.31321962 36.42822815 32.51933033]]

All machines at time step 1 (shape (10, 4)):
[[22.65846625 22.65863043 40.79212816 32.67434729]
 [19.55617275 26.1092259  13.49006423 28.75698018]
 [10.2147801  17.80155792 20.39361229 35.57122226]
 [33.12525822 38.56240029 24.27989878 35.03532898]
 [16.91506397 19.98242956 34.15402118 28.2875111 ]
 [23.38714288 29.04050857 43.86185901 26.74577813]
 [30.86857094 46.90455626 15.09463675 19.3370227 ]
 [27.59882794 32.81822872 12.63049289 11.79543387]
 [34.63376129 29.12780927 33.2206016  43.96792983]
 [22.76537215 32.14000494 29.73237625 24.27171087]]

Sensor 4 readings (shape (10, 5)):

## Task 4: Indexing a Tensor

In [5]:
X = np.arange(24).reshape(2, 3, 4)
print(f"X = np.arange(24).reshape(2, 3, 4)")
print(f"X:\n{X}")
print(f"\nShape of X: {X.shape}")

print(f"\nX[0] (shape {X[0].shape}):\n{X[0]}")
print(f"\nX[1] (shape {X[1].shape}):\n{X[1]}")
print(f"\nX[0, 0] (shape {X[0, 0].shape}):\n{X[0, 0]}")
print(f"\nX[0, 0, 0] (scalar): {X[0, 0, 0]}")

print("\nAnswers:")
print("  X[0] represents: The first block/matrix (all 3 rows, 4 columns) - shape (3, 4)")
print("  X[0,0] represents: The first row of the first block - shape (4,)")
print("  X[0,0,0] represents: The first element (scalar) - value 0")

X = np.arange(24).reshape(2, 3, 4)
X:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Shape of X: (2, 3, 4)

X[0] (shape (3, 4)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

X[1] (shape (3, 4)):
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

X[0, 0] (shape (4,)):
[0 1 2 3]

X[0, 0, 0] (scalar): 0

Answers:
  X[0] represents: The first block/matrix (all 3 rows, 4 columns) - shape (3, 4)
  X[0,0] represents: The first row of the first block - shape (4,)
  X[0,0,0] represents: The first element (scalar) - value 0


## Task 5: Slicing

In [6]:
X = np.arange(60).reshape(3, 4, 5)
print(f"X = np.arange(60).reshape(3, 4, 5)")
print(f"Shape: {X.shape}")

first_block = X[0]
print(f"\nFirst block X[0] (shape {first_block.shape}):\n{first_block}")

first_row_all = X[:, 0, :]
print(f"\nFirst row from every block X[:, 0, :] (shape {first_row_all.shape}):\n{first_row_all}")

third_element = X[:, :, 2]
print(f"\nThird element from every row/block X[:, :, 2] (shape {third_element.shape}):\n{third_element}")

last_two = X[:, :, -2:]
print(f"\nLast two elements along final dim X[:, :, -2:] (shape {last_two.shape}):\n{last_two}")

X = np.arange(60).reshape(3, 4, 5)
Shape: (3, 4, 5)

First block X[0] (shape (4, 5)):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

First row from every block X[:, 0, :] (shape (3, 5)):
[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]]

Third element from every row/block X[:, :, 2] (shape (3, 4)):
[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

Last two elements along final dim X[:, :, -2:] (shape (3, 4, 2)):
[[[ 3  4]
  [ 8  9]
  [13 14]
  [18 19]]

 [[23 24]
  [28 29]
  [33 34]
  [38 39]]

 [[43 44]
  [48 49]
  [53 54]
  [58 59]]]


## Task 6: Image Tensor

In [7]:
np.random.seed(42)
image = np.random.randint(0, 256, size=(128, 128, 3), dtype=np.uint8)

print(f"Image shape: {image.shape}")

red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]

print(f"Red channel shape: {red_channel.shape}")
print(f"Green channel shape: {green_channel.shape}")
print(f"Blue channel shape: {blue_channel.shape}")

print(f"Maximum pixel value: {image.max()}")
print(f"Minimum pixel value: {image.min()}")

Image shape: (128, 128, 3)
Red channel shape: (128, 128)
Green channel shape: (128, 128)
Blue channel shape: (128, 128)
Maximum pixel value: 255
Minimum pixel value: 0


## Task 7: Batch of Images

In [8]:
np.random.seed(42)
batch = np.random.randint(0, 256, size=(32, 128, 128, 3), dtype=np.uint8)

print(f"Batch shape: {batch.shape}")

first_img = batch[0]
print(f"\nFirst image shape: {first_img.shape}")

first_10 = batch[:10]
print(f"First 10 images shape: {first_10.shape}")

red_all = batch[:, :, :, 0]
print(f"Red channel from all images shape: {red_all.shape}")

pixel_50_50 = batch[:, 50, 50, :]
print(f"Pixel (50,50) from every image shape: {pixel_50_50.shape}")

Batch shape: (32, 128, 128, 3)

First image shape: (128, 128, 3)
First 10 images shape: (10, 128, 128, 3)
Red channel from all images shape: (32, 128, 128)
Pixel (50,50) from every image shape: (32, 3)


## Task 8: Reshape

In [9]:
X = np.arange(24)
print(f"Original X = np.arange(24), shape: {X.shape}, ndim: {X.ndim}")

shapes = [(4, 6), (2, 3, 4), (6, 4), (24,)]

for shape in shapes:
    reshaped = X.reshape(shape)
    print(f"\nReshaped to {shape}:")
    print(f"  Shape: {reshaped.shape}")
    print(f"  ndim: {reshaped.ndim}")
    print(f"  Tensor:\n{reshaped}")

print("\nWhy does reshaping change shape but not total elements?")
print("  Reshaping only changes the view/metadata (strides, shape) of the array.")
print("  The underlying data buffer (memory) remains unchanged.")
print("  Total elements = product of shape dimensions must remain constant.")
print("  This is why reshape requires the new shape to have the same total size.")

Original X = np.arange(24), shape: (24,), ndim: 1

Reshaped to (4, 6):
  Shape: (4, 6)
  ndim: 2
  Tensor:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshaped to (2, 3, 4):
  Shape: (2, 3, 4)
  ndim: 3
  Tensor:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Reshaped to (6, 4):
  Shape: (6, 4)
  ndim: 2
  Tensor:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Reshaped to (24,):
  Shape: (24,)
  ndim: 1
  Tensor:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Why does reshaping change shape but not total elements?
  Reshaping only changes the view/metadata (strides, shape) of the array.
  The underlying data buffer (memory) remains unchanged.
  Total elements = product of shape dimensions must remain constant.
  This is why reshape requires the new shape to have the same total size.


## Task 9: Reshape vs Transpose

In [10]:
X = np.arange(24).reshape(2, 3, 4)
print(f"Original X (shape {X.shape}):\n{X}")

X_reshaped = X.reshape(3, 2, 4)
print(f"\nX.reshape(3, 2, 4) (shape {X_reshaped.shape}):\n{X_reshaped}")

X_transposed = X.transpose(1, 0, 2)
print(f"\nX.transpose(1, 0, 2) (shape {X_transposed.shape}):\n{X_transposed}")

print(f"\nAre these the same? {np.array_equal(X_reshaped, X_transposed)}")

print("\nExplanation:")
print("  RESHAPE: Reinterprets the memory layout - changes shape but keeps")
print("           the same memory order (C-contiguous by default).")
print("           Elements are read in row-major order and filled into new shape.")
print("  TRANSPOSE: Permutes axes - changes the order of dimensions.")
print("             The data is rearranged so that axis 1 becomes axis 0,")
print("             axis 0 becomes axis 1, axis 2 stays axis 2.")
print("  They are fundamentally different operations!")

Original X (shape (2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

X.reshape(3, 2, 4) (shape (3, 2, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

X.transpose(1, 0, 2) (shape (3, 2, 4)):
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

Are these the same? False

Explanation:
  RESHAPE: Reinterprets the memory layout - changes shape but keeps
           the same memory order (C-contiguous by default).
           Elements are read in row-major order and filled into new shape.
  TRANSPOSE: Permutes axes - changes the order of dimensions.
             The data is rearranged so that axis 1 becomes axis 0,
             axis 0 becomes axis 1, axis 2 stays axis 2.
  They are fundamentally different operations!


## Task 10: Broadcasting

In [11]:
X = np.ones((3, 4))
b = np.array([10, 20, 30, 40])

print(f"X.shape = {X.shape}")
print(f"b.shape = {b.shape}")
print(f"X:\n{X}")
print(f"b: {b}")

result_add = X + b
print(f"\nX + b (shape {result_add.shape}):\n{result_add}")

result_mul = X * b
print(f"\nX * b (shape {result_mul.shape}):\n{result_mul}")

print("\nWhy can a (4,) tensor combine with a (3,4) tensor?")
print("  Broadcasting rules (from right to left):")
print("  1. Align shapes on the right: (3, 4) and (4,)")
print("  2. Dimensions are compatible if equal or one is 1")
print("  3. Missing dimensions on the left are treated as 1")
print("  4. b is treated as (1, 4) then broadcast to (3, 4)")
print("  5. The operation is performed element-wise")

X.shape = (3, 4)
b.shape = (4,)
X:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
b: [10 20 30 40]

X + b (shape (3, 4)):
[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]

X * b (shape (3, 4)):
[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]

Why can a (4,) tensor combine with a (3,4) tensor?
  Broadcasting rules (from right to left):
  1. Align shapes on the right: (3, 4) and (4,)
  2. Dimensions are compatible if equal or one is 1
  3. Missing dimensions on the left are treated as 1
  4. b is treated as (1, 4) then broadcast to (3, 4)
  5. The operation is performed element-wise


## Task 11: Broadcasting with Sensor Data

In [12]:
np.random.seed(42)
X = np.random.randn(100, 10) * 5 + 20
offsets = np.array([1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4])

print(f"X.shape = {X.shape} (100 samples × 10 sensors)")
print(f"offsets.shape = {offsets.shape}")
print(f"Offsets: {offsets}")

X_calibrated = X - offsets

print(f"\nX_calibrated.shape = {X_calibrated.shape}")
print(f"First sample before: {X[0]}")
print(f"First sample after:  {X_calibrated[0]}")
print(f"Offsets subtracted:  {X[0] - X_calibrated[0]}")

assert X_calibrated.shape == (100, 10), "Shape should remain (100, 10)"
print("\n✓ Output shape remains (100, 10) as required")

X.shape = (100, 10) (100 samples × 10 sensors)
offsets.shape = (10,)
Offsets: [1.2 0.8 1.1 0.5 0.9 1.  0.7 1.3 0.6 0.4]

X_calibrated.shape = (100, 10)
First sample before: [22.48357077 19.30867849 23.23844269 27.61514928 18.82923313 18.82931522
 27.89606408 23.83717365 17.65262807 22.71280022]
First sample after:  [21.28357077 18.50867849 22.13844269 27.11514928 17.92923313 17.82931522
 27.19606408 22.53717365 17.05262807 22.31280022]
Offsets subtracted:  [1.2 0.8 1.1 0.5 0.9 1.  0.7 1.3 0.6 0.4]

✓ Output shape remains (100, 10) as required


## Task 12: Tensor Aggregation

In [13]:
np.random.seed(42)
X = np.random.randn(100, 20, 5)

print(f"X.shape = {X.shape} (100 machines × 20 time steps × 5 sensors)")

print("\nPredicted shapes:")
print(f"  Mean across time (axis=1): (100, 5)")
print(f"  Mean across sensors (axis=2): (100, 20)")
print(f"  Mean across machines (axis=0): (20, 5)")
print(f"  Max across time (axis=1): (100, 5)")
print(f"  Std across time (axis=1): (100, 5)")

mean_time = X.mean(axis=1)
mean_sensors = X.mean(axis=2)
mean_machines = X.mean(axis=0)
max_time = X.max(axis=1)
std_time = X.std(axis=1)

print(f"\nActual shapes:")
print(f"  Mean across time: {mean_time.shape}")
print(f"  Mean across sensors: {mean_sensors.shape}")
print(f"  Mean across machines: {mean_machines.shape}")
print(f"  Max across time: {max_time.shape}")
print(f"  Std across time: {std_time.shape}")

X.shape = (100, 20, 5) (100 machines × 20 time steps × 5 sensors)

Predicted shapes:
  Mean across time (axis=1): (100, 5)
  Mean across sensors (axis=2): (100, 20)
  Mean across machines (axis=0): (20, 5)
  Max across time (axis=1): (100, 5)
  Std across time (axis=1): (100, 5)

Actual shapes:
  Mean across time: (100, 5)
  Mean across sensors: (100, 20)
  Mean across machines: (20, 5)
  Max across time: (100, 5)
  Std across time: (100, 5)


## Task 13: Normalize a Tensor

In [14]:
np.random.seed(42)
X = np.random.randn(100, 20, 5) * 10 + 50

print(f"Original X.shape = {X.shape}")
print(f"Original mean per sensor: {X.mean(axis=(0, 1))}")
print(f"Original std per sensor: {X.std(axis=(0, 1))}")

sensor_mean = X.mean(axis=(0, 1), keepdims=True)
sensor_std = X.std(axis=(0, 1), keepdims=True)

print(f"\nsensor_mean shape: {sensor_mean.shape}")
print(f"sensor_std shape: {sensor_std.shape}")

X_normalized = (X - sensor_mean) / sensor_std

print(f"\nNormalized X.shape = {X_normalized.shape}")
print(f"Normalized mean per sensor: {X_normalized.mean(axis=(0, 1))}")
print(f"Normalized std per sensor: {X_normalized.std(axis=(0, 1))}")

assert np.allclose(X_normalized.mean(axis=(0, 1)), 0, atol=1e-10)
assert np.allclose(X_normalized.std(axis=(0, 1)), 1, atol=1e-10)
print("\n✓ Verification passed: mean ≈ 0, std ≈ 1 for each sensor")

Original X.shape = (100, 20, 5)
Original mean per sensor: [49.9076781  50.1430176  49.91476813 49.6691053  50.2586317 ]
Original std per sensor: [10.21035898 10.23295347 10.07038588  9.84685831  9.79130368]

sensor_mean shape: (1, 1, 5)
sensor_std shape: (1, 1, 5)

Normalized X.shape = (100, 20, 5)
Normalized mean per sensor: [-3.49364981e-15 -5.14466247e-15  7.55440155e-15  5.04069009e-15
  6.46771525e-15]
Normalized std per sensor: [1. 1. 1. 1. 1.]

✓ Verification passed: mean ≈ 0, std ≈ 1 for each sensor


## Task 14: Flattening

In [15]:
np.random.seed(42)
image = np.random.randint(0, 256, size=(28, 28, 3), dtype=np.uint8)
print(f"Single image shape: {image.shape}")

flattened = image.reshape(-1)
print(f"Flattened shape: {flattened.shape}")
print(f"Expected: (2352,) - 28*28*3 = {28*28*3}")

batch = np.random.randint(0, 256, size=(64, 28, 28, 3), dtype=np.uint8)
print(f"\nBatch shape: {batch.shape}")

batch_flattened = batch.reshape(64, -1)
print(f"Batch flattened shape: {batch_flattened.shape}")
print(f"Expected: (64, 2352)")

print("\nWhy not flatten entire tensor to (150528,)?")
print("  - Would lose the batch structure (which sample is which)")
print("  - Cannot process samples independently in batch operations")
print("  - Loss of sample-level information for training/inference")
print("  - Batch dimension is needed for vectorized operations")
print("  - Model expects (batch_size, features) not (total_elements,)")

Single image shape: (28, 28, 3)
Flattened shape: (2352,)
Expected: (2352,) - 28*28*3 = 2352

Batch shape: (64, 28, 28, 3)
Batch flattened shape: (64, 2352)
Expected: (64, 2352)

Why not flatten entire tensor to (150528,)?
  - Would lose the batch structure (which sample is which)
  - Cannot process samples independently in batch operations
  - Loss of sample-level information for training/inference
  - Batch dimension is needed for vectorized operations
  - Model expects (batch_size, features) not (total_elements,)


## Task 15: Concatenation

In [16]:
np.random.seed(42)
visual_features = np.random.randn(32, 128)
sensor_features = np.random.randn(32, 64)

print(f"Visual features shape: {visual_features.shape}")
print(f"Sensor features shape: {sensor_features.shape}")

combined = np.concatenate([visual_features, sensor_features], axis=1)

print(f"Combined shape: {combined.shape}")
print(f"Expected: (32, 192) - 128 + 64 = 192")

print("\nWhy can we concatenate along feature dimension but not arbitrarily?")
print("  - Concatenation requires ALL other dimensions to match exactly")
print("  - Here: batch dimension (32) matches, so we can concat on axis=1")
print("  - Cannot concat on axis=0 because 128 ≠ 64")
print("  - Cannot concat on new axis without reshaping first")
print("  - The concatenation axis is where dimensions ADD; others must be equal")

Visual features shape: (32, 128)
Sensor features shape: (32, 64)
Combined shape: (32, 192)
Expected: (32, 192) - 128 + 64 = 192

Why can we concatenate along feature dimension but not arbitrarily?
  - Concatenation requires ALL other dimensions to match exactly
  - Here: batch dimension (32) matches, so we can concat on axis=1
  - Cannot concat on axis=0 because 128 ≠ 64
  - Cannot concat on new axis without reshaping first
  - The concatenation axis is where dimensions ADD; others must be equal


## Task 16: Practical Mini Challenge - Sensor Dataset

In [17]:
np.random.seed(42)
X = np.random.randn(500, 60, 8) * 10 + 50

print(f"Dataset shape: {X.shape}")

# 1. Extract machine 10
machine_10 = X[10]
print(f"\n1. Machine 10 shape: {machine_10.shape}")

# 2. Extract first 20 time steps
first_20_time = X[:, :20, :]
print(f"2. First 20 time steps shape: {first_20_time.shape}")

# 3. Extract sensor 5 from all machines
sensor_5 = X[:, :, 5]
print(f"3. Sensor 5 all machines shape: {sensor_5.shape}")

# 4. Average value of every sensor
avg_per_sensor = X.mean(axis=(0, 1))
print(f"4. Average per sensor: {avg_per_sensor}")

# 5. Average value at every time step
avg_per_time = X.mean(axis=(0, 2))
print(f"5. Average per time step shape: {avg_per_time.shape}")

# 6. Machine with highest average sensor reading
machine_avg = X.mean(axis=(1, 2))
best_machine = np.argmax(machine_avg)
print(f"6. Machine with highest avg: {best_machine} (avg={machine_avg[best_machine]:.2f})")

# 7. Normalize each sensor
sensor_mean = X.mean(axis=(0, 1), keepdims=True)
sensor_std = X.std(axis=(0, 1), keepdims=True)
X_normalized = (X - sensor_mean) / sensor_std
print(f"7. Normalized shape: {X_normalized.shape}")
print(f"   Normalized mean per sensor: {X_normalized.mean(axis=(0, 1))}")
print(f"   Normalized std per sensor: {X_normalized.std(axis=(0, 1))}")

# 8. Split into train/test
train = X[:400]
test = X[400:]
print(f"8. Train shape: {train.shape} (400 machines)")
print(f"   Test shape: {test.shape} (100 machines)")

Dataset shape: (500, 60, 8)



1. Machine 10 shape: (60, 8)
2. First 20 time steps shape: (500, 20, 8)
3. Sensor 5 all machines shape: (500, 60)
4. Average per sensor: [50.0509398  49.97287082 49.9542889  49.98380746 50.03957523 49.89664049
 50.09228703 50.07828965]
5. Average per time step shape: (60,)
6. Machine with highest avg: 338 (avg=51.22)
7. Normalized shape: (500, 60, 8)
   Normalized mean per sensor: [-5.42266232e-15 -1.38140166e-14 -3.29854218e-14  5.13774208e-14
  3.87930984e-15  4.33101185e-14  1.78231511e-14 -2.83740180e-14]
   Normalized std per sensor: [1. 1. 1. 1. 1. 1. 1. 1.]
8. Train shape: (400, 60, 8) (400 machines)
   Test shape: (100, 60, 8) (100 machines)


## Task 17: PyTorch

In [18]:
X = torch.arange(24).reshape(2, 3, 4)
print(f"X = torch.arange(24).reshape(2, 3, 4)")
print(f"X:\n{X}")
print(f"X.shape: {X.shape}")
print(f"X.ndim: {X.ndim}")
print(f"X.numel(): {X.numel()}")

X_large = torch.randn(32, 100, 768)
print(f"\nX_large = torch.randn(32, 100, 768)")
print(f"Shape: {X_large.shape}")

print("\nWhat could these three dimensions represent?")
print("  Option 1 (NLP/Transformers):")
print("    - 32: Batch size (number of sequences)")
print("    - 100: Sequence length (number of tokens)")
print("    - 768: Embedding dimension (e.g., BERT-base hidden size)")
print("  Option 2 (Time Series):")
print("    - 32: Batch size")
print("    - 100: Time steps")
print("    - 768: Features per time step")
print("  Option 3 (Video):")
print("    - 32: Batch size")
print("    - 100: Frames")
print("    - 768: Flattened frame features (e.g., 24x32=768)")

X = torch.arange(24).reshape(2, 3, 4)


X:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
X.shape: torch.Size([2, 3, 4])
X.ndim: 3
X.numel(): 24



X_large = torch.randn(32, 100, 768)
Shape: torch.Size([32, 100, 768])

What could these three dimensions represent?
  Option 1 (NLP/Transformers):
    - 32: Batch size (number of sequences)
    - 100: Sequence length (number of tokens)
    - 768: Embedding dimension (e.g., BERT-base hidden size)
  Option 2 (Time Series):
    - 32: Batch size
    - 100: Time steps
    - 768: Features per time step
  Option 3 (Video):
    - 32: Batch size
    - 100: Frames
    - 768: Flattened frame features (e.g., 24x32=768)
